### ISSUE TITLE
Criar favicon

### ISSUE THREAD

**Issue by codigocafe** [codigocafe/bonfim#3]
Criar o favicon com a logo do Bonfim para inserir no projeto.

**Comment by thiagoabcarvalho** [comment]
criei um favicon 94x94px em .png e coloquei na pasta _bonfim>front>public>assets>images_

**Comment by codigocafe** [comment]
Valeu pexe, vou adicionar no arquivo.

**Comment by codigocafe** [comment]
Favicon Aplicado.
